### ISSUE TITLE
[Snowboy library] trouble on compiling

### ISSUE THREAD

**Issue by bugsounet** [bugsounet/MMM-Hotword#140]
Hi,
We are building new `snowboy` library,
Since last update we don't use Kitt-AI snowboy library
Actually, i'm building my own library `npm`
it correct compiling error and many other

so **maybe** you can have some trouble

I any trouble, open issue, i will correct it

@bugsounet

**Comment by bretonesf** [comment]
Hi,

Hotword working fine so far, as I received the notification on my mirror that there was an update, I tried to update it.

Now problem : black screen.

If I try to npm start dev, it displays "devtools was disconnected from the page".

Here's what I have in Putty (sorry for the long copy-paste) : 

[2020-04-22 22:41:11.991] [LOG]    Starting MagicMirror: v2.11.0
[2020-04-22 22:41:12.004] [LOG]    Loading config ...
[2020-04-22 22:41:12.014] [LOG]    Loading module helpers ...
[2020-04-22 22:41:12.018] [LOG]    No helper found for module: alert.
[2020-04-22 22:41:12.100] [LOG]    Initializing new module helper ...
[2020-04-22 22:41:12.102] [LOG]    Module helper loaded: updatenotification
[2020-04-22 22:41:12.104] [LOG]    No helper found for module: clock.
[2020-04-22 22:41:12.787] [LOG]    Initializing new module helper ...
[2020-04-22 22:41:12.789] [LOG]    Module helper loaded: calendar
[2020-04-22 22:41:12.790] [LOG]    No helper found for module: compliments.
[2020-04-22 22:41:12.792] [LOG]    No helper found for module: currentweather.
[2020-04-22 22:41:12.793] [LOG]    No helper found for module: weatherforecast.
[2020-04-22 22:41:13.340] [LOG]    Initializing new module helper ...
[2020-04-22 22:41:13.341] [LOG]    Module helper loaded: MMM-Traffic
[2020-04-22 22:41:13.382] [LOG]    Initializing new module helper ...
[2020-04-22 22:41:13.383] [LOG]    Module helper loaded: newsfeed
[2020-04-22 22:41:13.388] [LOG]    Initializing new module helper ...
[2020-04-22 22:41:13.389] [LOG]    Module helper loaded: MMM-withings
[2020-04-22 22:41:15.442] [LOG]    Initializing new module helper ...
[2020-04-22 22:41:15.444] [LOG]    Module helper loaded: MMM-AssistantMk2
[2020-04-22 22:41:15.448] [LOG]    Initializing new module helper ...
[2020-04-22 22:41:15.449] [LOG]    Module helper loaded: MMM-Assistant2Display
[2020-04-22 22:41:15.461] [ERROR]  WARNING! Could not load config file. Starting                                                                                                                                                              with default configuration. Error found: Error: Cannot find module './lib/node/                                                                                                                                                             index.js'
Require stack:
- /home/pi/MagicMirror/modules/MMM-Hotword/node_modules/@bugsounet/snowboy/index                                                                                                                                                             .js
- /home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/mai                                                                                                                                                             n.js
-
[2020-04-22 22:41:15.463] [LOG]    Loading module helpers ...
[2020-04-22 22:41:15.465] [LOG]    No helper found for module: alert.
[2020-04-22 22:41:15.466] [LOG]    Initializing new module helper ...
[2020-04-22 22:41:15.467] [LOG]    Module helper loaded: updatenotification
[2020-04-22 22:41:15.468] [LOG]    No helper found for module: clock.
[2020-04-22 22:41:15.469] [LOG]    Initializing new module helper ...
[2020-04-22 22:41:15.469] [LOG]    Module helper loaded: calendar
[2020-04-22 22:41:15.471] [LOG]    No helper found for module: compliments.
[2020-04-22 22:41:15.472] [LOG]    No helper found for module: currentweather.
[2020-04-22 22:41:15.473] [LOG]    No helper found for module: weatherforecast.
[2020-04-22 22:41:15.474] [LOG]    Initializing new module helper ...
[2020-04-22 22:41:15.474] [LOG]    Module helper loaded: MMM-Traffic
[2020-04-22 22:41:15.475] [LOG]    Initializing new module helper ...
[2020-04-22 22:41:15.476] [LOG]    Module helper loaded: newsfeed
[2020-04-22 22:41:15.477] [LOG]    Initializing new module helper ...
[2020-04-22 22:41:15.477] [LOG]    Module helper loaded: MMM-withings
[2020-04-22 22:41:15.478] [LOG]    Initializing new module helper ...
[2020-04-22 22:41:15.478] [LOG]    Module helper loaded: MMM-AssistantMk2
[2020-04-22 22:41:15.479] [LOG]    Initializing new module helper ...
[2020-04-22 22:41:15.480] [LOG]    Module helper loaded: MMM-Assistant2Display
[2020-04-22 22:41:15.485] [ERROR]  App threw an error during load
[2020-04-22 22:41:15.486] [ERROR]  Error: Cannot find module './lib/node/index.j                                                                                                                                                             s'
Require stack:
- /home/pi/MagicMirror/modules/MMM-Hotword/node_modules/@bugsounet/snowboy/index                                                                                                                                                             .js
- /home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/mai                                                                                                                                                             n.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/elect                                                                                                                                                             ron/dist/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/modul                                                                                                                                                             e-alias/index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules                                                                                                                                                             /@bugsounet/snowboy/index.js:6:18)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
[2020-04-22 22:41:15.489] [LOG]    Whoops! There was an uncaught exception...
[2020-04-22 22:41:15.490] [ERROR]  Error: Cannot find module './lib/node/index.j                                                                                                                                                             s'
Require stack:
- /home/pi/MagicMirror/modules/MMM-Hotword/node_modules/@bugsounet/snowboy/index                                                                                                                                                             .js
- /home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/mai                                                                                                                                                             n.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/elect                                                                                                                                                             ron/dist/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/modul                                                                                                                                                             e-alias/index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules                                                                                                                                                             /@bugsounet/snowboy/index.js:6:18)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/@bugsounet/snowboy/in                                                                                                                                                             dex.js',
    '/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js',
    '/home/pi/MagicMirror/js/app.js',
    '/home/pi/MagicMirror/js/electron.js',
    '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/                                                                                                                                                             main.js',
    undefined
  ]
}

**Comment by bugsounet** [comment]
Do you try this:
```
cd ~/MagicMirror/modules/MMM-Hotword
git pull
npm run rebuild
```
it seens new library missing...

**Comment by bretonesf** [comment]
I did it as written in the "Update from 2.x.x to 2.3.0" part and had the problem after.

Just tried again now and it works again...dunno what's different. Anayway, thank you :)

**Comment by bugsounet** [comment]
perfect so
