### ISSUE TITLE
New update of MMM-Hotword creates blackscreen

### ISSUE THREAD

**Issue by Bronno** [bugsounet/MMM-Hotword#147]
Good afternoon,

I tried to install the different updates: HotWord,  GooglePhotoś, AssistantMk2, Assistant2Display. After that update $(npm bin)/electron-rebuild. There were many mistakes (problems with showboy etc....).

I restored the earlier version and that was working well. After updating ONLY HotWord, the "same" problemn (type of): black screen and "could not open config file": 
[2020-05-10 21:24:34.409] [LOG]    Starting MagicMirror: v2.11.0
[2020-05-10 21:24:34.419] [LOG]    Loading config ...
[2020-05-10 21:24:34.424] [LOG]    Loading module helpers ...
[2020-05-10 21:24:34.431] [ERROR]  WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module '@bugsounet/lpcm16'

I tried to update with electron-rebuild. After that I get more errors - the same like before restoring the older version: 

> magicmirror@2.11.0 start /home/pi/MagicMirror
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

[2020-05-10 21:24:34.409] [LOG]    Starting MagicMirror: v2.11.0
[2020-05-10 21:24:34.419] [LOG]    Loading config ...
[2020-05-10 21:24:34.424] [LOG]    Loading module helpers ...
[2020-05-10 21:24:34.431] [ERROR]  WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module '@bugsounet/lpcm16'
[2020-05-10 21:24:34.432] [LOG]    Loading module helpers ...
[2020-05-10 21:24:34.434] [ERROR]  App threw an error during load
[2020-05-10 21:24:34.435] [ERROR]  Error: Cannot find module '@bugsounet/lpcm16'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:9:16)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:254:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
[2020-05-10 21:24:34.436] [LOG]    Whoops! There was an uncaught exception...
[2020-05-10 21:24:34.436] [ERROR]  { Error: Cannot find module '@bugsounet/lpcm16'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:9:16)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:254:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10) code: 'MODULE_NOT_FOUND' }

My conclusion: the problem is in the update of MMM-HotWord. And why is it not possible to open the config file (I expect the config file in MagicMirror/config)? Can you tell me how I can solve that?
Thanks, Bronno

**Comment by bugsounet** [comment]
hi, Bronno

humm ... and What is your prefered command for updating ?

**Comment by Bronno** [comment]
I did the update with git pull....

**Comment by bugsounet** [comment]
ah, and what the ReadMe file says ?

**Comment by Bronno** [comment]
Ok, does it means that I have to add:

Updates 2.4.0 (2020-05-08)
use my new npm buffertowav library
use my new npm lpcm16 library

I had expected that an update includes these parts......The changes inside the update

**Comment by bugsounet** [comment]
ah, and you just read this ... ?

Me, i read [THIS](https://github.com/bugsounet/MMM-Hotword#update-from-23x-to-lasted) !

Read me simply says  ... there is a command to do ...
If you don't do the command it will never work !

**Comment by Bronno** [comment]
Ok, I got it working. By removing Hotword and AssistantMk2 and install
again. Thanks for your advice.

Op ma 11 mei 2020 17:45 schreef Cédric <notifications@github.com>:
